steps:
  build-push:
    image: woodpeckerci/plugin-docker-buildx
    when:
      branch: main
      event: push
    settings:
      registry: registry.default.svc.cluster.local:5000
      repo: registry.default.svc.cluster.local:5000/mirrorclip
      tags:
        - latest
        - "sha-${CI_COMMIT_SHA:0:8}"
      insecure: true
      cache_from: registry.default.svc.cluster.local:5000/mirrorclip:latest

  deploy:
    image: bitnami/kubectl
    when:
      branch: main
      event: push
    commands:
      # Tells K8s to re-download the latest image we just pushed
      - kubectl rollout restart deployment/k8s -n default
